# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master

  version: 0.0.1.{build}
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    
  configuration: Release

  #---------------------------------#
  #    environment configuration    #
  #---------------------------------#

  # Operating system (build VM template)
  os: Windows Server 2012

  #---------------------------------#
  #             build               #
  #---------------------------------#
  before_build: .\build\build.ps1 RestorePackages
  after_build: .\build\build.ps1 CreateNugetPackage

  #---------------------------------#
  #             tests               #
  #---------------------------------#
  test:
    assemblies:
      - Eventful.Tests.dll
      - SchoolReports.dll
      - EmergencyRoom.dll
    categories:
      - unit
      
  #---------------------------------#
  #          artifacts              #
  #---------------------------------#
  artifacts:
    - path: .\build\output.nupkg
      name: nuget
    
  #---------------------------------#
  #     deployment configuration    #
  #---------------------------------#
  deploy:
      # Deploying to NuGet feed
    - provider: NuGet
      api_key:
        secure: 3vo4lhJWIIqlhBnUGsj0FzO8lXcvKIIgdzflmAHMxDMgsoHe85HOMBr2W0LMYCWB
      artifact: output.nupkg
      
# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing
-
  branches:
    only:
      - dev
      
  version: 0.2.{build}
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    
  configuration: Release

  #---------------------------------#
  #    environment configuration    #
  #---------------------------------#

  # Operating system (build VM template)
  os: Windows Server 2012

  #---------------------------------#
  #             build               #
  #---------------------------------#
  before_build:
    - git submodule update --init
    - nuget restore src\Eventful.sln
    - nuget restore vendor\Neo4jClient\Neo4jClient.sln
  after_build: 
    ps: .\build\build.ps1 AppveyorPostBuild
  
  build:
    project: src\Eventful.sln
    verbosity: quiet

  #---------------------------------#
  #             tests               #
  #---------------------------------#
  test:
    assemblies:
      - Eventful.Tests.dll
      - Eventful.CsTests.dll
      - BookLibrary.dll
      - Eventful.Tests.Integration.dll
    categories:
      - unit
      - eventstore
      
  #---------------------------------#
  #          artifacts              #
  #---------------------------------#
  artifacts:
    - path: 'build\*.nupkg' # find all NuGet packages recursively
      name: eventful

  #---------------------------------#
  #          build cache            #
  #---------------------------------#
  cache:
      - src\packages
      - build\EventStore3
      - build\RavenDB
  #---------------------------------#
  #     deployment configuration    #
  #---------------------------------#
  deploy:
      # Deploying to NuGet feed
    - provider: NuGet
      api_key:
        secure: 3vo4lhJWIIqlhBnUGsj0FzO8lXcvKIIgdzflmAHMxDMgsoHe85HOMBr2W0LMYCWB
      artifact: eventful
